version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finzuu-company-service
    restart: always
    network_mode: host
    command: uvicorn app.main:app --host 127.0.0.1 --port 12041 --reload
    volumes:
      - ./:/finzuu
