from enum import Enum


class AppEnum(str, Enum):
    def __str__(self) -> str:
        return str.__str__(self)


class Permission(AppEnum):
    COMPANY_COMPANY_READ = "COMPANY-COMPANY-READ"
    COMPANY_COMPANY_CREATE = "COMPANY-COMPANY-CREATE"
    COMPANY_COMPANY_UPDATE = "COMPANY-COMPANY-UPDATE"
    COMPANY_COMPANY_ACTIVATE = "COMPANY-COMPANY-ACTIVATE"
    COMPANY_COMPANY_DEACTIVATE = "COMPANY-COMPANY-DEACTIVATE"

    COMPANY_LICENSE_READ = "COMPANY-LICENSE-READ"
    COMPANY_LICENSE_CREATE = "COMPANY-LICENSE-CREATE"
    COMPANY_LICENSE_UPDATE = "COMPANY-LICENSE-UPDATE"


class PackageName(AppEnum):
    ALL = "ALL"
    READY_CASH = "READY_CASH"
    READY_COLLECTE = "READY_COLLECTE"
    BULK = "BULK"


class CompanyType(AppEnum):
    MERCHANT = "MERCHANT"
    BANK = "BANK"
    IMF = "IMF"
    AGENCY = "AGENCY"
    KIOSK = "KIOSK"
    FUNDING_PROVIDER = "FUNDING_PROVIDER"
    FONDATION = "FONDATION"
